title: Persianov on Security
email: persianov.s@gmail.com
description: A research blog by Sveatoslav Persianov. Views on today's Cyber Security, Malware Analysis, Cyber Fraud investigations and insecurity in the Digital Era.
url: https://persianov.net
plugins:
    - jekyll-seo-tag
    - jekyll-relative-links
    - jekyll-paginate
    - jekyll-feed
relative_links:
    enabled: true
    collections: true
highlighter: rouge
paginate: 7
paginate_path: /page:num/
twitter:
    username: s_persianov
    card: summary_large_image
    creator: s_persianov
include: [.well-known]
