title: Persianov on Security
email: persianov.s@gmail.com
description: A research blog by Sveatoslav Persianov. Personal views on today's Cyber Security, Malware Analysis and Cyber Fraud investigations. Ideas about insecurity in the Digital Era.
url: https://persianov.net
plugins:
    - jekyll-seo-tag
    - jekyll-relative-links
    - jekyll-paginate
relative_links:
    enabled: true
    collections: true
highlighter: rouge
paginate: 7
paginate_path: /page:num/
twitter:
    username: s_persianov
    card: summary
