title: Persianov on Security
email: persianov.s@gmail.com
description: Personal views on today's CyberSecurity, Malware Analysis and Cyber Fraud investigations. Ideas about insecurity in the Digital Era, which affects more people every day.
# twitter_account: num1r0
# github_account: num1r0
plugins:
    - jekyll-seo-tag
    - jekyll-relative-links
    - jekyll-paginate
relative_links:
    enabled: true
    collections: true
highlighter: rouge
paginate: 7
paginate_path: /page:num/
twitter:
    username: num1r0
    card: summary
